

---
- hosts: all
  become: yes
  tasks:
  - name: Drain master node
    command: kubectl drain opnfv --delete-local-data --force --ignore-daemonsets
    ignore_errors: yes

  - name: Delete master node
    command: kubectl delete node opnfv
    ignore_errors: yes

  - name: Kubeadm reset (master)
    shell: yes y | sudo kubeadm reset

  - name: Delete /etc/cni/net.d/ (master)
    command: sudo rm -rf /etc/cni/net.d/

  - name: Delete $HOME/.kube/
    file:
      path: $HOME/.kube/
      state: absent
  
  - name: Delete Calico
    k8s:
      state: absent
      definition: '{{ item }}'
    with_items: '{{ lookup("url", "https://docs.projectcalico.org/manifests/calico.yaml", split_lines=False) | from_yaml_all | list }}'
    when: item is not none
  
  - name: Delete Kube-flannel
    k8s:
      state: absent
      definition: "{{ lookup('file', 'kube-flannel-daemonset.yml') }}"


