---
- hosts: all
  become: yes
  tasks:
  - name: Initializing Kubernetes cluster
    become: yes
    command: kubeadm init --apiserver-advertise-address=10.10.120.22 --pod-network-cidr=10.244.0.0/16
    register: output
  
  - name: .kube directory creation in $HOME/
    file:
      path: $HOME/.kube
      state: directory

  - name: Copying required files
    shell: |
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
  
